name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - name: Install Dependencies
        run: cd typetrail && npm install
      - name: Build Project
        run: cd typetrail && npm run build
      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./typetrail/dist
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./typetrail/dist
          user_name: 'sunny[bot]'
          user_email: '40462053+sunnydodti@users.noreply.github.com'
          commit_message: 'Deploy to GitHub Pages'